/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Cliente;
import model.ClienteTableModel;

/**
 *
 * @author edvan
 */
public class TelaEdicao extends javax.swing.JInternalFrame {
    ClienteTableModel modelo = new ClienteTableModel();
    
    /*função para limpar os campos da tela*/
    public void limpaCampo(){
        caixa_edicao_CPF.setText("");
        caixa_edicao_RG.setText("");
        caixa_edicao_celular.setText("");
        caixa_edicao_endereco.setText("");
        caixa_edicao_nascimento.setText("");
        caixa_edicao_nome.setText("");
    }
    /*função para ativar e desaticar os campos e botões da tela*/
    public void ativaDesativaCampo(boolean nome, boolean nascimento, boolean rg,
            boolean cpf, boolean endereco,boolean celular, boolean tabela,
            boolean novo, boolean salvar, boolean editar, boolean excluir, boolean cancelar){
        caixa_edicao_nome.setEnabled(nome);
        caixa_edicao_nascimento.setEnabled(nascimento);
        caixa_edicao_RG.setEnabled(rg);
        caixa_edicao_CPF.setEnabled(cpf);
        caixa_edicao_endereco.setEnabled(endereco);
        caixa_edicao_celular.setEnabled(celular);
        tabela_edicao.setEnabled(tabela);
        
        btn_edicao_novo.setEnabled(novo);
        btn_edicao_salvar.setEnabled(salvar);
        btn_edicao_editar.setEnabled(editar);
        btn_edicao_excluir.setEnabled(excluir);
        btn_edicao_cancelar.setEnabled(cancelar);
        
    }
    /**
     * Creates new form TelaCadastro
     */
    public TelaEdicao() {
        initComponents();
        tabela_edicao.setModel(modelo);
        ativaDesativaCampo(false, false, false, false, false, false, false, true, false, false, false, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        caixa_edicao_nome = new javax.swing.JTextField();
        caixa_edicao_endereco = new javax.swing.JTextField();
        caixa_edicao_nascimento = new javax.swing.JFormattedTextField();
        caixa_edicao_RG = new javax.swing.JFormattedTextField();
        caixa_edicao_CPF = new javax.swing.JFormattedTextField();
        caixa_edicao_celular = new javax.swing.JFormattedTextField();
        btn_edicao_editar = new javax.swing.JButton();
        btn_edicao_cancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_edicao = new javax.swing.JTable();
        btn_edicao_excluir = new javax.swing.JButton();
        btn_edicao_salvar = new javax.swing.JButton();
        btn_edicao_novo = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jTextField3.setText("jTextField3");

        jFormattedTextField5.setText("jFormattedTextField5");

        jButton3.setText("jButton3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Cadastro de Clientes");
        setName(""); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");

        jLabel2.setText("Nascimento");

        jLabel3.setText("RG");

        jLabel4.setText("CPF");

        jLabel5.setText("Endereço");

        jLabel6.setText("Celular");

        try {
            caixa_edicao_nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            caixa_edicao_RG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            caixa_edicao_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            caixa_edicao_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_edicao_editar.setText("Editar");
        btn_edicao_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edicao_editarActionPerformed(evt);
            }
        });

        btn_edicao_cancelar.setText("Cancelar");
        btn_edicao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edicao_cancelarActionPerformed(evt);
            }
        });

        tabela_edicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela_edicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_edicaoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_edicao);

        btn_edicao_excluir.setText("Excluir");
        btn_edicao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edicao_excluirActionPerformed(evt);
            }
        });

        btn_edicao_salvar.setText("Salvar");
        btn_edicao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edicao_salvarActionPerformed(evt);
            }
        });

        btn_edicao_novo.setText("Novo");
        btn_edicao_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edicao_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(caixa_edicao_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(caixa_edicao_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(caixa_edicao_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(caixa_edicao_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btn_edicao_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_edicao_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_edicao_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btn_edicao_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btn_edicao_cancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(caixa_edicao_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(caixa_edicao_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixa_edicao_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixa_edicao_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixa_edicao_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixa_edicao_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixa_edicao_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixa_edicao_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edicao_editar)
                    .addComponent(btn_edicao_cancelar)
                    .addComponent(btn_edicao_excluir)
                    .addComponent(btn_edicao_salvar)
                    .addComponent(btn_edicao_novo))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 721, 425);

        setBounds(0, 0, 738, 447);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_edicao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edicao_cancelarActionPerformed
        limpaCampo();
        dispose();
    }//GEN-LAST:event_btn_edicao_cancelarActionPerformed

    private void btn_edicao_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edicao_editarActionPerformed
        if(tabela_edicao.getSelectedRow() != -1){
            tabela_edicao.setValueAt(caixa_edicao_nome.getText(), tabela_edicao.getSelectedRow(), 0);
            tabela_edicao.setValueAt(caixa_edicao_nascimento.getText(), tabela_edicao.getSelectedRow(), 1);
            tabela_edicao.setValueAt(caixa_edicao_RG.getText(), tabela_edicao.getSelectedRow(), 2);
            tabela_edicao.setValueAt(caixa_edicao_CPF.getText(), tabela_edicao.getSelectedRow(), 3);
            tabela_edicao.setValueAt(caixa_edicao_endereco.getText(), tabela_edicao.getSelectedRow(), 4);
            tabela_edicao.setValueAt(caixa_edicao_celular.getText(), tabela_edicao.getSelectedRow(), 5);
            limpaCampo();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um item para alterar.");

        }
    }//GEN-LAST:event_btn_edicao_editarActionPerformed

    private void btn_edicao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edicao_salvarActionPerformed
        Cliente cliente = new Cliente();
        cliente.setNome(caixa_edicao_nome.getText());
        cliente.setNascimento(caixa_edicao_nascimento.getText());
        cliente.setRg(caixa_edicao_RG.getText());
        cliente.setCpf(caixa_edicao_CPF.getText());
        cliente.setEndereco(caixa_edicao_endereco.getText());
        cliente.setEndereco(caixa_edicao_endereco.getText());
        cliente.setCelular(caixa_edicao_celular.getText());
        modelo.addRow(cliente);
        limpaCampo();
        ativaDesativaCampo(false, false, false, false, false, false, true, true, false, false, false, true);
    }//GEN-LAST:event_btn_edicao_salvarActionPerformed

    private void btn_edicao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edicao_excluirActionPerformed
        if(tabela_edicao.getSelectedRow() != -1){
            modelo.removeRow(tabela_edicao.getSelectedRow());
            limpaCampo();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir.");
        }
    }//GEN-LAST:event_btn_edicao_excluirActionPerformed

    private void tabela_edicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_edicaoMouseClicked
        if(tabela_edicao.getSelectedRow() != -1){
            caixa_edicao_nome.setText(modelo.getValueAt(tabela_edicao.getSelectedRow(), 0).toString());
            caixa_edicao_nascimento.setText(modelo.getValueAt(tabela_edicao.getSelectedRow(), 1).toString());
            caixa_edicao_RG.setText(modelo.getValueAt(tabela_edicao.getSelectedRow(), 2).toString());
            caixa_edicao_CPF.setText(modelo.getValueAt(tabela_edicao.getSelectedRow(), 3).toString());
            caixa_edicao_endereco.setText(modelo.getValueAt(tabela_edicao.getSelectedRow(), 4).toString());
            caixa_edicao_celular.setText(modelo.getValueAt(tabela_edicao.getSelectedRow(), 5).toString());
            ativaDesativaCampo(true, true, true, true, true, true, true, true, true, true, true, true);

        }
    }//GEN-LAST:event_tabela_edicaoMouseClicked

    private void btn_edicao_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edicao_novoActionPerformed
        ativaDesativaCampo(true, true, true, true, true, true, true, false, true, false, false, true);
    }//GEN-LAST:event_btn_edicao_novoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edicao_cancelar;
    private javax.swing.JButton btn_edicao_editar;
    private javax.swing.JButton btn_edicao_excluir;
    private javax.swing.JButton btn_edicao_novo;
    private javax.swing.JButton btn_edicao_salvar;
    private javax.swing.JFormattedTextField caixa_edicao_CPF;
    private javax.swing.JFormattedTextField caixa_edicao_RG;
    private javax.swing.JFormattedTextField caixa_edicao_celular;
    private javax.swing.JTextField caixa_edicao_endereco;
    private javax.swing.JFormattedTextField caixa_edicao_nascimento;
    private javax.swing.JTextField caixa_edicao_nome;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tabela_edicao;
    // End of variables declaration//GEN-END:variables
}
