/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author edvan
 */
public class TelaLogin extends javax.swing.JFrame {

   /* função que contem o usuario e a senha.*/
   public boolean checkLogin(String login, String senha) {
        return login.equals("admin") && senha.equals("admin");
    }
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        caixa_login_usuario = new javax.swing.JTextField();
        caixa_login_senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_login_entrar = new javax.swing.JButton();
        btn_login_sair = new javax.swing.JButton();
        TelaLogin_fundo = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);
        getContentPane().add(caixa_login_usuario);
        caixa_login_usuario.setBounds(380, 200, 130, 20);
        getContentPane().add(caixa_login_senha);
        caixa_login_senha.setBounds(380, 260, 130, 20);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 160, 70, 30);

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 220, 70, 40);

        btn_login_entrar.setText("Entrar");
        btn_login_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login_entrar);
        btn_login_entrar.setBounds(370, 300, 63, 23);

        btn_login_sair.setText("Sair");
        btn_login_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login_sair);
        btn_login_sair.setBounds(460, 300, 60, 23);

        TelaLogin_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagem_fundo_login.jpg"))); // NOI18N
        getContentPane().add(TelaLogin_fundo);
        TelaLogin_fundo.setBounds(-10, 0, 610, 360);

        setSize(new java.awt.Dimension(590, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_entrarActionPerformed
        /*verificando se o usuario e a senha são os mesmo da função cheakLogin*/
        if(checkLogin(caixa_login_usuario.getText(), new String(caixa_login_senha.getPassword()))){
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Usuario ou senha Invalidos!");
        }
    }//GEN-LAST:event_btn_login_entrarActionPerformed

    private void btn_login_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_login_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaLogin_fundo;
    private javax.swing.JButton btn_login_entrar;
    private javax.swing.JButton btn_login_sair;
    private javax.swing.JPasswordField caixa_login_senha;
    private javax.swing.JTextField caixa_login_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
